### ISSUE TITLE
e2e test for SGT

### ISSUE THREAD

**Issue by blockchaindevsh** [ethstorage/optimism#101]

**Comment by qizhou** [comment]
A list of manual tests is done here: https://perfect-amphibian-929.notion.site/SWC-Devnet-1282e493e88380648486d4961eb91a8d

To be more specific, we want to test
- SGT without native balance.  The SGT balance difference should equal to tx cost.
- Full SGT payment with the native balance
- Partial SGT payment with native balance, where SGT becomes zero, and the rest of gas is paid by native.  This ensures that as long as SGT + native balance >= tx cost, we will always accept the tx
- Insufficient gas with both SGT and native balance, i.e.,  SGT + native balance < tx cost

Besides these, we should also check whether the balances of the vaults (fee recipients) are expected.

**Comment by pochenai** [comment]
Done in https://github.com/ethstorage/optimism/pull/125
