### ISSUE TITLE
CircleCI: action [op-program-compat] failed

### ISSUE THREAD

**Issue by qzhodl** [ethstorage/optimism#110]
In the op-program folder, the `make verify-compat` command failed due to the addition of a new `FetchReceipts` call in the [getTxSucceed](https://github.com/ethstorage/optimism/blob/577eabbca745736709553a08a31c84897e0cf0ee/op-node/rollup/derive/blob_data_source.go#L77) function.

To address this, we may need to:
 - Add an option to avoid using the batchInbox contract, allowing us to reuse the preimage oracle data to pass the test.
 - Generate new preimage data for the batchInbox case.

**Comment by blockchaindevsh** [comment]
Fixed by https://github.com/ethstorage/optimism/pull/122
