### ISSUE TITLE
CircleCI: action [contracts-bedrock-checks] failed

### ISSUE THREAD

**Issue by qzhodl** [ethstorage/optimism#111]
[Failed page](https://app.circleci.com/pipelines/circleci/VJoJbnHRXJiFR13mWFvRfZ/SHyYDZiLFYMtveJSZVFKbw/24/workflows/01ee261b-f023-4a74-84b6-d6c2453b6fbd/jobs/243)

**Comment by syntrust** [comment]
The following PRs together would fix `contracts-bedrock-checks`:

- https://github.com/ethstorage/optimism/pull/128
- https://github.com/ethstorage/optimism/pull/132
- https://github.com/ethstorage/optimism/pull/135
- https://github.com/ethstorage/optimism/pull/129
- https://github.com/ethstorage/optimism/pull/138
