### ISSUE TITLE
Sync block is delayed

### ISSUE THREAD

**Issue by iteyelmp** [ethstorage/optimism#46]
After a period of time, the running testnet node's synchronized block number is 50387 less than the latest block number in the network. Restarting the node cannot catch up the gap.

**Comment by qzhodl** [comment]
Are there any log screenshots that can be attached?

**Comment by iteyelmp** [comment]
<img width="1381" alt="image" src="https://github.com/user-attachments/assets/7585cca2-9829-4770-b8e7-dede87e71e94">
<img width="1600" alt="image" src="https://github.com/user-attachments/assets/252a5456-df1a-428d-9c00-71eb8d251619">
<img width="920" alt="image" src="https://github.com/user-attachments/assets/02666334-818d-4e86-b008-e0d84e61f94b">

**Comment by blockchaindevsh** [comment]
Fixed with `p2p.sync.onlyreqtostatic` flag .
