### ISSUE TITLE
need methods to withdraw SGT

### ISSUE THREAD

**Issue by qizhou** [ethstorage/optimism#70]
We need `withdraw()` and `batchWithdrwa()` that burn the SGT and return the native token to owner/burner.  It is the counter operation of `deposit()` and `batchDeposit()` where deposit methods are used for airdrop.  When such airdrop are expired (e.g., SGT are not used after 4 years), we may expire the SGT and withdraw the native token for other active users (as specified by our airdrop terms).

**Comment by blockchaindevsh** [comment]
Just to confirm, is it only required when `IS_BACKED_BY_NATIVE` is `true` ?

**Comment by qizhou** [comment]
> Just to confirm, is it only required when `IS_BACKED_BY_NATIVE` is `true` ?

Yes, the same as `deposit()`.  If not backed by native, then `burnFrom()` would be used.

**Comment by qizhou** [comment]
Should we close this issue?

**Comment by blockchaindevsh** [comment]
> Should we close this issue?

Yeah
