### ISSUE TITLE
Gaslimit is not fixed

### ISSUE THREAD

**Issue by iteyelmp** [ethstorage/optimism#99]
The same function of the same contract passes in the same parameters. Sometimes the gas used is [487w](https://explorer.testnet.l2.quarkchain.io/tx/0x585219e0e0fecbfca037255fb7b54e66b0e4ffa032b38b91d051cb185e4d39d0), sometimes it is [160w](https://explorer.testnet.l2.quarkchain.io/tx/0xbc1059ea72b9edd6c526189182bbbbbc37292041de741c28cc1b30b75550c5bb). 

The difference is: 
more than 4 million transactions are submitted in batches, and the block is full, 
while more than 1 million transactions are submitted linearly, one transaction per block.

**Comment by blockchaindevsh** [comment]
You mentioned that the parameters are the same, but it seems not, there're diffs when I stored the parameters into a file and diff:

```
diff 487.txt 160.txt
```

**Comment by iteyelmp** [comment]
> You mentioned that the parameters are the same, but it seems not, there're diffs when I stored the parameters into a file and diff:
> 
> ```
> diff 487.txt 160.txt
> ```

What I mean by the same is that 560 addresses are submitted every time. The address length is fixed, the quantity is fixed, and the content changes. Therefore, gas fluctuates, but the fluctuation will not be too large.

**Comment by qizhou** [comment]
> You mentioned that the parameters are the same, but it seems not, there're diffs when I stored the parameters into a file and diff:
> 
> ```
> diff 487.txt 160.txt
> ```

What is the actual diff here?

**Comment by blockchaindevsh** [comment]
> > You mentioned that the parameters are the same, but it seems not, there're diffs when I stored the parameters into a file and diff:
> > ```
> > diff 487.txt 160.txt
> > ```
> 
> What is the actual diff here?

(deleted because too long)

**Comment by qizhou** [comment]
> The same function of the same contract passes in the same parameters. Sometimes the gas used is [487w](https://explorer.testnet.l2.quarkchain.io/tx/0x585219e0e0fecbfca037255fb7b54e66b0e4ffa032b38b91d051cb185e4d39d0), sometimes it is [160w](https://explorer.testnet.l2.quarkchain.io/tx/0xbc1059ea72b9edd6c526189182bbbbbc37292041de741c28cc1b30b75550c5bb).
> 
> The difference is: more than 4 million transactions are submitted in batches, and the block is full, while more than 1 million transactions are submitted linearly, one transaction per block.

Which network (and RPC) for the test?

**Comment by iteyelmp** [comment]
<img width="1101" alt="image" src="https://github.com/user-attachments/assets/db2d87e7-679e-4550-b755-52b1c0af0725">
<img width="453" alt="image" src="https://github.com/user-attachments/assets/f28e1f0a-d234-4d8c-87f8-c1baec784096">

<img width="871" alt="image" src="https://github.com/user-attachments/assets/19996a5f-7d45-4841-849c-5a7469043abc">

https://explorer.testnet.l2.quarkchain.io/tx/0x27121af2b158a7fea8e2e06e4375437190d619da26f0a3ef02354a5bb4eebc91

<img width="878" alt="image" src="https://github.com/user-attachments/assets/8e9dc9c6-98c9-477b-91af-75a8bf32cfe8">

https://explorer.testnet.l2.quarkchain.io/tx/0x83c7c4c38ce4c1daade627bf4044b6504d4323e84f053a04ae02237d0032d891

You can look at these two transactions. The gas used is 477w and 1430w. The data returned through rpc is also consistent with the browser.

**Comment by iteyelmp** [comment]
> <img alt="image" width="1101" src="https://private-user-images.githubusercontent.com/6647261/392217381-db2d87e7-679e-4550-b755-52b1c0af0725.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyODQzMDAsIm5iZiI6MTczMzI4NDAwMCwicGF0aCI6Ii82NjQ3MjYxLzM5MjIxNzM4MS1kYjJkODdlNy02NzllLTQ1NTAtYjc1NS01MmIxYzBhZjA3MjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDRUMDM0NjQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjBkMGM4YTlkYmY3NTFhZjEwNWViZGFkMDY1MTc4ODZmNmY2MGI3YjMxMmU4YmIzM2QwMDNhZjY1MjEzNDBlOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.R4A7nYYJ5mBYKztT5mmcwR7tjYMnKukPP5aaXp_VbwY"> <img alt="image" width="453" src="https://private-user-images.githubusercontent.com/6647261/392217424-f28e1f0a-d234-4d8c-87f8-c1baec784096.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyODQzMDAsIm5iZiI6MTczMzI4NDAwMCwicGF0aCI6Ii82NjQ3MjYxLzM5MjIxNzQyNC1mMjhlMWYwYS1kMjM0LTRkOGMtODdmOC1jMWJhZWM3ODQwOTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDRUMDM0NjQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGQ2YTQxMmI5MDdhOWE0ZDU0ZmZkM2M2YjEyMTI4YzVlNDlmMmJiMDY3ZDdiMjI4ZTZjZTAyYTg4YjE1ZGU4MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.GYnATCfLqxYJN_KEh1bry_Oc3fM0Lc5pC5p5QBvr0fE"> <img alt="image" width="871" src="https://private-user-images.githubusercontent.com/6647261/392218119-19996a5f-7d45-4841-849c-5a7469043abc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyODQzMDAsIm5iZiI6MTczMzI4NDAwMCwicGF0aCI6Ii82NjQ3MjYxLzM5MjIxODExOS0xOTk5NmE1Zi03ZDQ1LTQ4NDEtODQ5Yy01YTc0NjkwNDNhYmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDRUMDM0NjQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjlmZjQ0NjViNWFhODZlNTg0MzFjNzdkMTFkNzFlYjkxOGQwNmI3ZGQ3MDEzNDExNzJjMDE3MTdkYTlmZTczMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.yraGQulTL_8fFwgH1juOn_ihi73gdSxH0VIOQ4XlnR0">
> https://explorer.testnet.l2.quarkchain.io/tx/0x27121af2b158a7fea8e2e06e4375437190d619da26f0a3ef02354a5bb4eebc91
> 
> <img alt="image" width="878" src="https://private-user-images.githubusercontent.com/6647261/392218168-8e9dc9c6-98c9-477b-91af-75a8bf32cfe8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyODQzMDAsIm5iZiI6MTczMzI4NDAwMCwicGF0aCI6Ii82NjQ3MjYxLzM5MjIxODE2OC04ZTlkYzljNi05OGM5LTQ3N2ItOTFhZi03NWE4YmYzMmNmZTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDRUMDM0NjQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDk4NTJmNjljOTZhYTg3YjVhMDJjYTM2MjY3OTljNzAyYjAxNmI4ZTM0Zjc3YmM4NzQ5MzMyMjdhODRlYmY0NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.y3_Oa13HVO2Ggs2_g3_0SrK6zWnEUuIYL6efsRH3GHU">
> https://explorer.testnet.l2.quarkchain.io/tx/0x83c7c4c38ce4c1daade627bf4044b6504d4323e84f053a04ae02237d0032d891
> 
> You can look at these two transactions. The gas used is 477w and 1430w. The data returned through rpc is also consistent with the browser.

Their parameters are all 560 wallet addresses

**Comment by qizhou** [comment]
Actually, the first tx https://explorer.testnet.l2.quarkchain.io/tx/0x585219e0e0fecbfca037255fb7b54e66b0e4ffa032b38b91d051cb185e4d39d0?tab=token_transfers is a **first-mint** tx, which costs higher gas.  E.g., https://explorer.testnet.l2.quarkchain.io/address/0x3e2aEe8908aE892977FbC4a02cf836A48e254efb?tab=token_transfers where you can see
<img width="1536" alt="image" src="https://github.com/user-attachments/assets/44011324-ab82-4536-86a7-9ad6b2e4a3f8">

The second tx https://explorer.testnet.l2.quarkchain.io/tx/0xbc1059ea72b9edd6c526189182bbbbbc37292041de741c28cc1b30b75550c5bb is not a **first-mint** tx, whose gas will be lower.  E.g.,

https://explorer.testnet.l2.quarkchain.io/address/0xA6D49b6b34C616056B71C3fC3a259Dfd4646cE7f?tab=token_transfers

where 

<img width="1564" alt="image" src="https://github.com/user-attachments/assets/e87636bf-39c9-4102-96a1-9abf29eca79a">


The difference will be at least 20,000-5,000=15,000 per mint.  Taking 100 mints per tx, the gas diff will be > 1,500,000.

**Comment by blockchaindevsh** [comment]
> The difference will be at least 20,000-5,000=15,000 per mint. Taking 100 mints per tx, the gas diff will be > 1,500,000.

Where does `20,000-5,000` come from?

**Comment by qizhou** [comment]
SSTORE gas cost for first-time writing is 20,000.  The second time writing for non-zero data is 5,000.

**Comment by blockchaindevsh** [comment]
> SSTORE gas cost for first-time writing is 20,000. The second time writing for non-zero data is 5,000.

But the first tx in a block doesn't mean first-time writing, only the globally first tx is the first time, right?

**Comment by qizhou** [comment]
> > SSTORE gas cost for first-time writing is 20,000. The second time writing for non-zero data is 5,000.
> 
> But the first tx in a block doesn't mean first-time writing, only the globally first tx is the first time, right?

Yes, and you can check whether the tx is for first-time writing from the link I provided.
